<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Card type' => 'Kartentyp',
    'Select' => 'Wählen Sie Ihre Karte aus',
    'Visa' => 'Visa',
    'Mastercard' => 'Mastercard',
    'JCB' => 'JCB',
    'American Express' => 'American Express',
    'Expiry Date' => 'Gültig bis',
    'Month' => 'Monat',
    'Year' => 'Jahr',
    'Amount to bill' => 'Summe',
    'Your full name' => 'Kundenname',
    'Name on card' => 'Name des Karteninhabers(genau wie auf der Karte angegeben)',
    'Submit' => 'Senden',
    'Secure Credit Card Form' => 'Gesichertes Kreditkartenzahlungsformular',
    "Please inform your bank or credit card issuer that you will be receiving a charge from China. " => 'Bitte informieren Sie Ihr Kreditkarteninstitut darüber, dass Sie eine Zahlungsaufforderung aus China erhalten werden.',
    'Success' => 'Success',
    'Thank you.' => 'Vielen Dank. Wir haben Ihre Kreditkarteninformationen erhalten.',
    'We have received your credit card information. Your agent will contact you once we have charged your credit card.' => 'Ihr Reiseberater wird Sie während unserer Bürozeiten kontaktieren, sobald wir Ihre Kreditkarte belastet haben.',
    'BACK TO PREVIOUS PAGE' => 'Zurück zur The China Guide-Hauptseite',
    'Required' => 'Bitte füllen Sie alle Felder aus',
    'Card number' => 'Kartennummer',
    'Card security code' => 'Sicherheitsnummer (drei- oder vierstellige Zahl auf Kartenrückseite)',
    'Amount to bill' => 'Summe',
    'Billing address' => 'Rechnungsadresse',
    'Your phone number' => 'Kontaktnummer (Festnetz oder Mobil)',
    'Your email' => 'Emailadresse',
    'Card holder\'s email' => 'Emailadresse des Karteninhabers',
    'Your travel agent' => 'Berater',
    'Your tour start date' => 'Tourbeginn',
    'Donate to {0}Animals Asia{1}' => 'Spenden an {0}Animals Asia{1}',
    'Other amount' => 'Anderer Betrag',
    'I have read and agree to the {0}Terms of Service{1}' => 'Ich habe die {0}Geschäftsbedingungen{1} gelesen und bin mit diesen einverstanden',
];
