<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Card type' => 'Tipo de tarjeta',
    'Select' => 'Seleccione',
    'Visa' => 'Visa',
    'Mastercard' => 'Mastercard',
    'JCB' => 'JCB',
    'American Express' => 'American Express',
    'Expiry Date' => 'Fecha de expiración',
    'Month' => 'Mes',
    'Year' => 'Año',
    'Amount to bill' => 'Monto a facturar',
    'Your full name' => 'Nombre del cliente',
    'Name on card' => 'Nombre en la tarjeta de crédito',
    'Submit' => 'Enviar',
    'Secure Credit Card Form' => 'Formulario de pago seguro',
    "Please inform your bank or credit card issuer that you will be receiving a charge from China. " => 'Por favor, informe a su banco de que va a recibir un cobro desde China. ',
    'Success' => 'Success',
    'Thank you.' => 'Gracias. Hemos recibido la información de su tarjeta de crédito.',
    'We have received your credit card information. Your agent will contact you once we have charged your credit card.' => 'Su agente se pondrá en contacto con usted cuando hayamos realizado el cobro en horario de oficina.',
    'BACK TO PREVIOUS PAGE' => 'Volver a la página inicial de The China Guide',
    'Required' => 'Todos los campos son obligatorios',
    'Card number' => 'Número de la tarjeta de crédito',
    'Card security code' => 'Código de seguridad de la tarjeta (3 ó 4 cifras en la parte trasera de la tarjeta de crédito)',
    'Amount to bill' => 'Monto a facturar',
    'Billing address' => 'Dirección de Facturación',
    'Your phone number' => 'Teléfono (contacto)',
    'Your email' => 'Email',
    'Card holder\'s email' => 'Email del dueño de la tarjeta',
    'Your travel agent' => 'Agente de viajes',
    'Your tour start date' => 'Fecha del Tour',
    'Donate to {0}Animals Asia{1}' => 'Donar a {0}Animals Asia{1}',
    'Other amount' => 'Otra Cantidad',
    'I have read and agree to the {0}Terms of Service{1}' => 'He leído y estoy de acuerdo con los {0}términos de servicio{1}',
];
