<?php
return [
    'uploads_url' => UPLOADS_URL,
    'language_name' => array(
        'en' => 'English',
        'fr' => 'Français',
        'es' => 'Español',
        'de' => 'Deutsch',
        'pt' => 'Português',
        ),
    'currency_name' => array(
        'USD' => ['sign'=>'$' ,'name'=>'USD'],
        'EUR' => ['sign'=>'€' ,'name'=>'EUR'],
        'GBP' => ['sign'=>'£' ,'name'=>'GBP'],
        'CNY' => ['sign'=>'¥' ,'name'=>'CNY'],
        ),
    'biz_type'    => array(
        BIZ_TYPE_CITIES     => 'cities',
        BIZ_TYPE_TOUR       => 'tour',
        BIZ_TYPE_ITINERARY  => 'itinerary',
        BIZ_TYPE_ALBUM      => 'album',
        ),

    'rec_type' => array(
        REC_TYPE_MUST_VISIT           => Yii::t('app', 'Must Visit'),
        REC_TYPE_POPULAR              => Yii::t('app', 'Popular'),
        REC_TYPE_OFF_THE_BEATEN_TRACK => Yii::t('app', 'Off the Beaten Track'),
        ),
    'tour_themes' => array(
        TOUR_THEMES_MOST_POPULAR => 'Most Popular',
        TOUR_THEMES_FAMILY       => 'Family Vacation',
        TOUR_THEMES_CULTURE      => 'Chinese Culture',
        TOUR_THEMES_ADVENTUROUS  => 'Adventurous',
        TOUR_THEMES_FOODIE       => 'Foodie',
        TOUR_THEMES_AT_A_GLANCE  => 'At a Glance',
        // TOUR_THEMES_POPULAR_CITY  => 'Popular City Tours',
        // TOUR_THEMES_NATURE      => 'Nature',
        // TOUR_THEMES_CRUISE      => 'Cruise',
        // TOUR_THEMES_ROMANTIC    => 'Romantic',
        ),
    'months' => array(
        1 => 'Jan',
        2 => 'Feb',
        3 => 'Mar',
        4 => 'Apr',
        5 => 'May',
        6 => 'Jun',
        7 => 'Jul',
        8 => 'Aug',
        9 => 'Sep',
        10 => 'Oct',
        11 => 'Nov',
        12 => 'Dec',
        ),
    'article_type' => array(
        ARTICLE_TYPE_ARTICLE        => 'Article',
        ARTICLE_TYPE_ADVERTISEMENT  => 'Advertisement',
        ARTICLE_TYPE_FAQ            => 'FAQ',
        ARTICLE_TYPE_PREPARATION    => 'Preparation',
        ),
    'faq_type' => array(
        FAQ_TYPE_TRIP_PLANNING => 'Trip Planning',
        FAQ_TYPE_IN_CHINA      => 'In China',
        ),
    'album_type' => array(
        ALBUM_TYPE_SIGHT    => 'sight',
        ALBUM_TYPE_ACTIVITY => 'activity',
        ),
    'dis_status' => array(
        DIS_STATUS_SHOW => 'Show',
        DIS_STATUS_HIDE => 'Hide',
        ),
    'form_types' => array(
        FORM_TYPE_CUSTOM => 'custom',
        FORM_TYPE_QUOTATION => 'quotation',
        FORM_TYPE_EDU => 'educational',
        FORM_TYPE_MICE => 'MICE',
        ),
    'form_required' => array(
        FORM_TYPE_CUSTOM => array(
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'adults',
            'group_type',
            'name_prefix',
            'name',
            'email',
            'nationality',
            'prefered_travel_agent',
        ),
        FORM_TYPE_QUOTATION => array(
            'arrival_date',
            'arrival_city',
            'adults',
            'book_hotels',
            'name_prefix',
            'name',
            'email',
            'nationality',
            'prefered_travel_agent',
        ),
        FORM_TYPE_EDU => array(
            'subject_program',
            'participants_number',
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'ideas',
            'name_prefix',
            'name',
            'email',
            'school_name',
            'position',
        ),
        FORM_TYPE_MICE => array(
            'purpose_trip',
            'number_participants',
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'ideas_trip',
            'name_prefix',
            'name',
            'email',
            'position',
            'company_name',
        ),
    ),
    'form_fields' => array(
        FORM_TYPE_CUSTOM => array(
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'adults',
            'children',
            'infants',
            'guest_information',
            'group_type',
            'cities_plan',
            'travel_interests',
            'prefered_budget',
            'additional_information',
            'name_prefix',
            'name',
            'email',
            'nationality',
            'prefered_travel_agent',
        ),
        FORM_TYPE_QUOTATION => array(
            'tour_code',
            'tour_name',
            'arrival_date',
            'arrival_city',
            'adults',
            'children',
            'infants',
            'guest_information',
            'book_hotels',
            'hotel_preferences',
            'room_requirements',
            'additional_information',
            'name_prefix',
            'name',
            'email',
            'nationality',
            'prefered_travel_agent',
        ),
        FORM_TYPE_EDU => array(
            'subject_program',
            'participants_number',
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'ideas',
            'name_prefix',
            'name',
            'email',
            'school_name',
            'position',
            'phone_number',
            'hear_about_us',
        ),
        FORM_TYPE_MICE => array(
            'purpose_trip',
            'number_participants',
            'arrival_date',
            'arrival_city',
            'departure_date',
            'departure_city',
            'ideas_trip',
            'name_prefix',
            'name',
            'email',
            'position',
            'company_name',
            'phone_number',
            'hear_about_us',
        ),
    ),

];

