<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Card type' => '',
    'Visa' => '',
    'Mastercard' => '',
    'American Express' => '',
    'Expiry Date' => '',
    'Month' => '',
    'Year' => '',
    'Amount to bill' => '',
    'Your full name' => '',
    'Name on card' => '',
    'Submit' => '',
    'Secure Credit Card Form' => '',
    "Please inform your bank or credit card issuer that you will be receiving a charge from China. " => '',
    'Success' => '',
    'Thank you.' => '',
    'We have received your credit card information. Your agent will contact you once we have charged your credit card.' => '',
    'BACK TO PREVIOUS PAGE' => '',
    'Required' => '',
    'ID' => '',
    'Your full name' => '',
    'Card number' => '',
    'Card security code' => '',
    'Amount to bill' => '',
    'Billing address' => '',
    'Your phone number' => '',
    'Your email' => '',
    'Card holder\'s email' => '',
    'Your travel agent' => '',
    'Your tour start date' => '',

];
