<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Card type' => 'Type de carte',
    'Visa' => 'Visa',
    'Mastercard' => 'Mastercard',
    'American Express' => 'American Express',
    'JCB' => 'JCB',
    'Expiry Date' => 'Date d\'expiration',
    'Month' => 'Mois',
    'Year' => 'Année',
    'Amount to bill' => 'Montant à facturer',
    'Your full name' => 'Nom du client',
    'Name on card' => 'Nom inscrit sur la carte',
    'Submit' => 'Soumettre',
    'Secure Credit Card Form' => 'Formulaire de paiement sécurisé',
    "Please inform your bank or credit card issuer that you will be receiving a charge from China. " => 'S\'il vous plaît infomez votre banque qu\'un paiement pour la Chine va être effectué.',
    'Success' => 'Success',
    'Thank you.' => 'Merci, nous avons bien reçu les renseignements relatifs à votre carte de crédit.',
    'We have received your credit card information. Your agent will contact you once we have charged your credit card.' => 'Votre agent vous contactera une fois que nous aurons effectivement débité votre carte pendant nos horaires d\'ouverture au public.',
    'BACK TO PREVIOUS PAGE' => 'Retour à la page d\'accueil de The China Guide',
    'Required' => 'Tous les champs sont obligatoires',
    'Card number' => 'Numéro de carte bancaire',
    'Card security code' => 'Code de sécurité de la carte (3 ou 4 chiffres au dos de la carte bancaire)',
    'Amount to bill' => 'Montant à facturer',
    'Billing address' => 'Adresse de facturation',
    'Your phone number' => 'Téléphone ',
    'Your email' => 'Email',
    'Card holder\'s email' => 'Email du payeur',
    'Your travel agent' => 'Agent de voyages',
    'Your tour start date' => 'Date du circuit',
    'Select' => 'Selectionnez',
    'Donate to Animals Asia' => 'faire une donation à Animals Asia',
    'Other amount' => 'autre montant',

];